#!/bin/sh

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 image_file" >&2
	exit 1
fi

resolution=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')

convert $1 -contrast -resize $resolution\! RGB:- | i3lock -u --raw $resolution:rgb --image /dev/stdin
