#!/bin/sh
set -e

img_cache="/tmp/lock.png"
img_lock="${HOME}/.images/lock"


if [ ! -f "$img_cache" ]; then
    resolution=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')
    convert "$img_lock" -contrast -resize "$resolution"\! "$img_cache"
fi

xkb-switch -s us
i3lock -u -i "$img_cache"
