#!/bin/bash
MAX_UNREAD=5

# Set maildirs
mdir="$HOME/data/Mail"
mboxes="$mdir/gitlab/new/ $mdir/inbox/new/ $mdir/inbox-ext/new/ \
        $mdir/redmine/new/ $mdir/xpon/new/"

counter=$(find $mboxes -type f | wc -l)
symbol="░"

if [ $counter -ge $MAX_UNREAD ]; then
    symbol="▓"
    counter=$MAX_UNREAD
fi

for (( i=1; i<=$counter; i++ ))
do
    echo -ne "$symbol"
done
