#!/bin/bash
MAX_UNREAD=7
MAX_SHOW_BRIGHT=4

# Set maildirs
mdir="$HOME/data/Mail"
mboxes="$mdir/gitlab/new/ $mdir/inbox/new/ $mdir/inbox-ext/new/ \
        $mdir/redmine/new/ $mdir/xpon/new/"

counter=$(find $mboxes -type f | wc -l)
symbol="▓"

if [ $counter -ge $MAX_UNREAD ]; then
    counter=$MAX_SHOW_BRIGHT
    symbol=" "
fi

for (( i=1; i<=$counter; i++ ))
do
    echo -ne "$symbol"
done
