#!/bin/bash
MAX_SHOW=3

# Set maildirs
mdir="$HOME/data/Mail"
mboxes="$mdir/mattermost/new/"

symbol="█"

counter=$(find $mboxes -type f | wc -l)
if [ $counter -ge $MAX_SHOW ]; then
    counter=$MAX_SHOW
fi

for (( i=1; i<=$counter; i++ ))
do
    echo -ne "$symbol"
done
