#!/bin/sh
ws_to_switch=$1
ws_current=$(~/.bin/i3/ws_name)

#if [ $ws_to_switch = $ws_current ] && [ $ws_current = "tmp" ]; then
if  [ $ws_current = "tmp" ] && [[ $ws_current == $ws_to_switch ]]; then
	i3-msg workspace back_and_forth
else
    i3-msg workspace $ws_to_switch
fi
