#! /bin/sh

xte "mousemove 0 0"
sxhkd &

#bspc rule -a "*" split_dir=south

bspc config focus_follows_pointer false
bspc config pointer_follows_focus false

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

bspc config border_width        1
bspc config window_gap          0
bspc config ignore_ewmh_focus   true
#bspc config auto_cancel         false
#bspc config auto_alternate      false

#bspc config focused_border_color  "#587965"
bspc config focused_border_color  "#4f6c5a"
#bspc config focused_border_color  "#2f583f"
#bspc config focused_border_color  "#222222"
bspc config normal_border_color   "#222222"
bspc config presel_feedback_color "#222222"

bspc config split_ratio         0.5
bspc config single_monocle      true
bspc config borderless_monocle  true
bspc config paddingless_monocle true
bspc config gapless_monocle     true
#bspc wm --record-history off
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config click_to_focus no

bspc monitor -d 1 2 9 0

bspc desktop ^1 -l monocle
bspc desktop ^2 -l monocle
bspc desktop ^3 -l monocle
bspc desktop ^4 -l monocle

# for java gui
#bspc rule -a "window-MainFrame" state=floating
#export _JAVA_AWT_WM_NONREPARENTING=1
#export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

# scratchpad
#bspc rule -a scratchpad state=floating hidden=on sticky=on
#~/.bin/menu/all/st_scratchpad &
